// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDSSqwWznjz9UtvciopgTg6zq-gPtp44',
    appId: '1:833430374558:android:6c4573c69b41ac5d78138f',
    messagingSenderId: '833430374558',
    projectId: 'lost-found-app-4f90b',
    storageBucket: 'lost-found-app-4f90b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJDSSqwWznjz9UtvciopgTg6zq-gPtp44',
    appId: '1:833430374558:ios:6c4573c69b41ac5d78138f',
    messagingSenderId: '833430374558',
    projectId: 'lost-found-app-4f90b',
    storageBucket: 'lost-found-app-4f90b.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJDSSqwWznjz9UtvciopgTg6zq-gPtp44',
    appId: '1:833430374558:ios:6c4573c69b41ac5d78138f',
    messagingSenderId: '833430374558',
    projectId: 'lost-found-app-4f90b',
    storageBucket: 'lost-found-app-4f90b.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDSSqwWznjz9UtvciopgTg6zq-gPtp44',
    appId: '1:833430374558:web:6c4573c69b41ac5d78138f',
    messagingSenderId: '833430374558',
    projectId: 'lost-found-app-4f90b',
    authDomain: 'lost-found-app-4f90b.firebaseapp.com',
    storageBucket: 'lost-found-app-4f90b.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJDSSqwWznjz9UtvciopgTg6zq-gPtp44',
    appId: '1:833430374558:web:6c4573c69b41ac5d78138f',
    messagingSenderId: '833430374558',
    projectId: 'lost-found-app-4f90b',
    authDomain: 'lost-found-app-4f90b.firebaseapp.com',
    storageBucket: 'lost-found-app-4f90b.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAJDSSqwWznjz9UtvciopgTg6zq-gPtp44',
    appId: '1:833430374558:web:6c4573c69b41ac5d78138f',
    messagingSenderId: '833430374558',
    projectId: 'lost-found-app-4f90b',
    authDomain: 'lost-found-app-4f90b.firebaseapp.com',
    storageBucket: 'lost-found-app-4f90b.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
